# Generated by Django 3.2.8 on 2021-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='Локация')),
                ('mobile', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=64, verbose_name='мыло')),
                ('address', models.TextField(verbose_name='дрес')),
            ],
        ),
    ]
